### ISSUE TITLE
A copy of the dataset?

### ISSUE THREAD

**Issue by vmoens** [google-research/batch_rl#34]
Hi team!
First thanks a mil for the amazing work!
[TorchRL](https://github.com/pytorch/rl) is working on providing an easy, out-of-the-box API to get offline RL datasets such as this one.
We were wondering what the license was for your data?
Could we create a copy in a different format on our bucket to make it available to the users without the need to install gcloud?

**Comment by agarwl** [comment]
Can you also post a link to the `torchrl` dataset here so that I can update [offline-rl.github.io](https://offline-rl.github.io). Btw, there's also a [tfds version of the dataset](https://colab.sandbox.google.com/github/google-research/rlds/blob/main/rlds/examples/tfds_rlu_atari.ipynb):  It's same as the Atari replay dataset but released as part of RL Unplugged benchmark.
