### ISSUE TITLE
Retraining the online agent

### ISSUE THREAD

**Issue by n17s** [google-research/batch_rl#8]
I'd like to retrain the online DQN agent in order to log some additional data during online training. The README says 

> This data can be generated by running the online agents using batch_rl/baselines/train.py for 200 million frames (standard protocol)

However, this is not enough information to accurately replicate the setup. Could you share the gin file that was used? Is it the same as [the one in dopamine](https://github.com/google/dopamine/blob/master/dopamine/agents/dqn/configs/dqn.gin)?

Also, is there a faster way to accurately replicate the *online* training and logging via the RL unplugged project, or is it just the offline part that has become faster?

**Comment by agarwl** [comment]
Yes, it is the same as original gin config in dopamine. The agents in `LoggedDQNAgent` in this repo [here](https://github.com/google-research/batch_rl/tree/master/batch_rl/baselines) were used to collect the data. You can just use the `run_experiment.py` script to launch these experiments.

Regarding the online training replication, [Acme](https://github.com/deepmind/acme) might have a faster version of training online agents too (not sure how fast it is since the bottleneck is online data collection from Atari environments). RL Unplugged creates TFRecord version of the offline Atari dataset, so it only focuses on the offline part.  That said, logging experiments would take about 4-5 days per game run for online Atari with Dopamine.

**Comment by n17s** [comment]
This is very helpful! Thanks!
